[package]
name = "diesel_timings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.2.4", features = ["postgres"] }
uuid = { version = "1.11.0", features = ["v4"] }
